USE atlzoo;

CREATE TABLE IF NOT EXISTS EXHIBIT (
Size INT NOT NULL,
Water_Feature TINYINT(1) NOT NULL,
Name VARCHAR(20),
PRIMARY KEY(Name));
# Comment to grading TA
# For Water_Feature, value of zero is false, Non­zero values are considered true
CREATE TABLE IF NOT EXISTS ANIMAL (
Age INT NOT NULL,
Type ENUM('Mammal', 'Bird', 'Reptile', 'Amphibian', 'Arthropod', 'Fish') NOT NULL,
Species VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Exhibit VARCHAR(20) NOT NULL,
PRIMARY KEY (Name, Species),
FOREIGN KEY (Exhibit) REFERENCES EXHIBIT(Name) ON UPDATE CASCADE ON
DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS ADMINS (
Username VARCHAR(20),
Password VARCHAR(20) NOT NULL,
Email VARCHAR(30) NOT NULL,
PRIMARY KEY (Username) );

CREATE TABLE IF NOT EXISTS VISITORS (
Username VARCHAR(20),
Password VARCHAR(20) NOT NULL,
Email VARCHAR(30) NOT NULL,
PRIMARY KEY (Username) );

CREATE TABLE IF NOT EXISTS STAFF (
Username VARCHAR(20),
Password VARCHAR(20) NOT NULL,
Email VARCHAR(30) NOT NULL,
PRIMARY KEY (Username) );

CREATE TABLE IF NOT EXISTS SHOWS (
Name VARCHAR(20),
Date_and_time DATETIME,
Located_at VARCHAR(20) NOT NULL,
Host VARCHAR(20) NOT NULL,
PRIMARY KEY(Name, Date_and_time),
FOREIGN KEY(Located_at) REFERENCES EXHIBIT(Name) ON UPDATE CASCADE
ON DELETE RESTRICT,
	FOREIGN KEY(Host) REFERENCES STAFF(Username) ON UPDATE CASCADE ON
DELETE CASCADE);

CREATE TABLE IF NOT EXISTS NOTE (
Time TIMESTAMP NOT NULL,
Text TEXT,
Username VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Species VARCHAR(20) NOT NULL,
Staff_email VARCHAR(30) NOT NULL,
PRIMARY KEY (Time, Username, Name, Species, Staff_email),
FOREIGN KEY (Username) REFERENCES STAFF(Username) ON UPDATE
CASCADE ON DELETE CASCADE,
FOREIGN KEY (Name, Species) REFERENCES ANIMAL(Name, Species) ON UPDATE CASCADE
ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS VISIT_SHOW(
Shows_name VARCHAR(20) NOT NULL,
Visitor_username VARCHAR(20) NOT NULL,
Visitor_Email VARCHAR(30) NOT NULL,
Time TIMESTAMP NOT NULL,
PRIMARY KEY (Time, Visitor_username, Shows_name),
FOREIGN KEY (Shows_name) REFERENCES SHOWS(Name) ON UPDATE
CASCADE ON DELETE CASCADE,
FOREIGN KEY (Visitor_username) REFERENCES VISITORS(Username) ON UPDATE
CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS VISIT_EXHIBIT(
Datetime TIMESTAMP NOT NULL,
Exhibit_name VARCHAR(20) NOT NULL,
Visitor_username VARCHAR(20) NOT NULL,
Visitor_Email VARCHAR(30) NOT NULL,
PRIMARY KEY(Datetime, Exhibit_name, Visitor_username),
FOREIGN KEY (Exhibit_name) REFERENCES EXHIBIT(Name) ON UPDATE
CASCADE ON DELETE RESTRICT,
FOREIGN KEY (Visitor_username) REFERENCES VISITORS(Username) ON UPDATE
CASCADE ON DELETE CASCADE);